USE [ShareablePlanner]
GO

/****** Object:  Table [dbo].[PERSON]    Script Date: 12/10/2022 9:24:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSON](
	[PERSON_ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSON_USER_NAME] [varchar](50) NOT NULL,
	[PERSON_PASSWORD] [varchar](50) NOT NULL,
	[PERSON_EMAIL] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PERSON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


