USE [ShareablePlanner]
GO

/****** Object:  Table [dbo].[SCHEDULE]    Script Date: 12/10/2022 9:24:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SCHEDULE](
	[SCHEDULE_ID] [int] IDENTITY(1,1) NOT NULL,
	[SCHEDULE_DESCRIPTION] [varchar](225) NULL,
	[PERSON_ID] [int] NOT NULL,
	[YMD] [varchar](50) NOT NULL,
	[TIME] [varchar](50) NULL,
	[SCHEDULE_NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SCHEDULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SCHEDULE]  WITH CHECK ADD FOREIGN KEY([PERSON_ID])
REFERENCES [dbo].[PERSON] ([PERSON_ID])
GO


